#!/usr/bin/python

import unittest
from time import ctime
from test_mathfunc import TestMathFunc
from HTMLTestRunner import HTMLTestRunner

if __name__ == '__main__':
	suite = unittest.TestSuite()
	
	tests = [TestMathFunc('test_add'), TestMathFunc('test_minus'), TestMathFunc('test_divide')]
	suite.addTests(tests)
	
	#suite = unittest.makeSuite(TestMathFunc)
	
#	runner = unittest.TextTestRunner(verbosity=2)

#	with open('UnittestTextReport.txt', 'a') as f:
#		runner = unittest.TextTestRunner(stream=f, verbosity=2)
#		runner.run(suite)
#		f.write('-----------' + ctime() + '-----------\n\n\n')

	with open('unittest.html', 'w') as f:
		runner = HTMLTestRunner(stream=f,
								title='MathFunc Test Report',
								description='generated by HTMLTestRunner.',
								verbosity=2)
		runner.run(suite)
